# Generated by Django 6.0 on 2026-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chat_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
